apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms2
  template:
    metadata:
      labels:
        app: ms2
    spec:
      containers:
      - name: ms2
        image: kinnar0112/ms2:1.0
        ports:
        - containerPort: 3001