apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms3-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms3
  template:
    metadata:
      labels:
        app: ms3
    spec:
      containers:
      - name: ms3
        image: kinnar0112/ms3:1.0
        ports:
        - containerPort: 3002